"""Render a parsed Teradata table as BigQuery / Redshift / Synapse DDL, plus a DuckDB simulator DDL."""

from __future__ import annotations

import re

from .models import (
    ColumnMapping,
    Conversion,
    SourceObject,
    TableMeta,
    TargetId,
    TdBaseType,
)
from .td_catalog import INTEGER_TYPES
from .typemap import duckdb_type, map_type

T = TdBaseType


def target_schema(database: str, schema_map: dict[str, str]) -> str:
    return schema_map.get(database.upper(), database.lower() or "migrated")


def q(target: TargetId, *parts: str) -> str:
    if target == "bigquery":
        return "`" + ".".join(parts) + "`"
    if target == "synapse":
        return ".".join(f"[{p}]" for p in parts)
    return ".".join(f'"{p.lower()}"' if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", p) else p.lower() for p in parts)


def ident(target: TargetId, name: str) -> str:
    return name.lower() if target == "redshift" else name


def _sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def _default(value: str | None, base: TdBaseType, target: TargetId) -> str | None:
    if value is None:
        return None
    v = value.strip()
    u = v.upper()
    if u in ("CURRENT_DATE", "DATE"):
        return "CURRENT_DATE()" if target == "bigquery" else ("CAST(GETDATE() AS DATE)" if target == "synapse" else "CURRENT_DATE")
    if u.startswith("CURRENT_TIMESTAMP"):
        if target == "bigquery":
            return "CURRENT_DATETIME()"
        return "SYSDATETIME()" if target == "synapse" else "GETDATE()"
    if u == "USER":
        return None
    if m := re.fullmatch(r"(DATE|TIMESTAMP)\s*('[^']*')", v, re.IGNORECASE):
        if target == "synapse":
            return m.group(2)
        if target == "bigquery" and m.group(1).upper() == "TIMESTAMP" and base == T.TIMESTAMP:
            return f"DATETIME {m.group(2)}"
        return f"{m.group(1).upper()} {m.group(2)}"
    return v


def column_mappings(table: TableMeta, target: TargetId) -> list[ColumnMapping]:
    out = []
    for c in table.columns:
        m = map_type(c, target)
        out.append(ColumnMapping(column=c.name, td_type=c.td_type, target_type=m.type, nullable=c.nullable, lossy=m.lossy, note=m.note))
    return out


def _bq_partition(table: TableMeta, warnings: list[str]) -> str | None:
    if not table.partition_columns:
        return None
    col = table.column(table.partition_columns[0])
    if col is None:
        return None
    expr = table.partition_expression or ""
    if col.base_type == T.DATE:
        grain = "MONTH" if re.search(r"INTERVAL\s*'1'\s*MONTH", expr, re.IGNORECASE) else "DAY"
        return f"DATE_TRUNC({col.name}, {grain})" if grain == "MONTH" else col.name
    if col.base_type == T.TIMESTAMP:
        return f"DATETIME_TRUNC({col.name}, DAY)"
    if col.base_type in INTEGER_TYPES:
        warnings.append(f"Integer partition on {col.name} -> RANGE_BUCKET; review bucket bounds")
        return f"RANGE_BUCKET({col.name}, GENERATE_ARRAY(0, 100000000, 100000))"
    warnings.append(f"Partition column {col.name} ({col.td_type}) cannot partition in BigQuery; clustered only")
    return None


def render_table(obj: SourceObject, target: TargetId, schema_map: dict[str, str]) -> Conversion:
    t = obj.table
    assert t is not None
    schema = target_schema(t.database, schema_map)
    rules: list[str] = []
    warnings: list[str] = []
    fqn = q(target, schema, ident(target, t.name))
    lines: list[str] = []
    ci_cols: list[str] = []
    for c in t.columns:
        m = map_type(c, target)
        if m.lossy and m.note:
            warnings.append(f"{c.name}: {m.note}")
        name = ident(target, c.name)
        col = f"{q(target, name) if target != 'redshift' else name} {m.type}"
        if c.identity:
            if target == "bigquery":
                warnings.append(f"{c.name}: IDENTITY not supported -> populate with GENERATE_UUID()/ROW_NUMBER() in the load")
                rules.append("IDENTITY -> plain INT64 (surrogate key generated by load)")
            elif target == "redshift":
                col = f"{name} BIGINT IDENTITY({c.identity.start},{c.identity.increment})"
                rules.append("GENERATED AS IDENTITY -> IDENTITY(seed,step)")
            else:
                col += f" IDENTITY({c.identity.start},{c.identity.increment})"
                rules.append("GENERATED AS IDENTITY -> IDENTITY(seed,step) (values not guaranteed sequential)")
        d = _default(c.default, c.base_type, target)
        if d is not None and not c.identity:
            col += f" DEFAULT {d}"
        if not c.nullable:
            col += " NOT NULL"
        if c.comment and target == "bigquery":
            col += f" OPTIONS(description={_sql_str(c.comment)})"
        lines.append(col)
        if c.compress_values:
            rules.append("COMPRESS dropped (target uses automatic columnar compression)")
        if c.format:
            rules.append("FORMAT phrase dropped (presentation only; apply in queries/BI)")
        if c.case_specific is False and target in ("bigquery", "redshift"):
            ci_cols.append(c.name)
    if ci_cols:
        warnings.append(f"NOT CASESPECIFIC columns become case-sensitive: {', '.join(ci_cols)}")
    pk = t.unique_keys[0] if t.unique_keys else []
    pk_cols = [ident(target, c) for c in pk]
    if t.kind == "SET":
        warnings.append("SET table: duplicate-row rejection is not enforced on target; dedupe in load")
        rules.append("SET -> regular table + de-duplication in the load step")
    if t.secondary_indexes:
        rules.append("Secondary indexes dropped (not applicable on target)")
    if t.foreign_keys:
        rules.append("Foreign keys emitted as informational (NOT ENFORCED)")

    body = ",\n    ".join(lines)
    suffix: list[str] = []
    if target == "bigquery":
        if pk_cols:
            body += f",\n    PRIMARY KEY ({', '.join(pk_cols)}) NOT ENFORCED"
            rules.append("UNIQUE PRIMARY INDEX -> PRIMARY KEY NOT ENFORCED")
        part = _bq_partition(t, warnings)
        if part:
            suffix.append(f"PARTITION BY {part}")
            rules.append("PARTITION BY RANGE_N -> PARTITION BY date column")
        cluster = [c for c in t.primary_index if c not in t.partition_columns][:4] or t.primary_index[:4]
        if cluster:
            suffix.append(f"CLUSTER BY {', '.join(cluster)}")
            rules.append("PRIMARY INDEX -> CLUSTER BY")
        if t.comment:
            suffix.append(f"OPTIONS(description={_sql_str(t.comment)})")
        sql = f"CREATE TABLE IF NOT EXISTS {fqn} (\n    {body}\n)" + ("".join(f"\n{s}" for s in suffix)) + ";"
        if not t.partition_columns and t.partition_expression:
            warnings.append("Partition expression not mapped")
    elif target == "redshift":
        if pk_cols:
            body += f",\n    PRIMARY KEY ({', '.join(pk_cols)})"
            rules.append("UNIQUE PRIMARY INDEX -> PRIMARY KEY (informational)")
        if t.primary_index:
            suffix.append(f"DISTSTYLE KEY DISTKEY ({ident(target, t.primary_index[0])})")
            rules.append("PRIMARY INDEX -> DISTKEY (first PI column)")
        else:
            suffix.append("DISTSTYLE AUTO")
        sort = t.partition_columns or t.primary_index
        if sort:
            suffix.append(f"COMPOUND SORTKEY ({', '.join(ident(target, c) for c in sort)})")
            rules.append("Partitioning / PI -> SORTKEY")
        sql = f"CREATE TABLE IF NOT EXISTS {fqn} (\n    {body}\n)" + "".join(f"\n{s}" for s in suffix) + ";"
        if t.comment:
            sql += f"\nCOMMENT ON TABLE {fqn} IS {_sql_str(t.comment)};"
        for c in t.columns:
            if c.comment:
                sql += f"\nCOMMENT ON COLUMN {fqn}.{ident(target, c.name)} IS {_sql_str(c.comment)};"
    else:
        if pk_cols:
            body += f",\n    CONSTRAINT [PK_{t.name}] PRIMARY KEY NONCLUSTERED ({', '.join(f'[{c}]' for c in pk_cols)}) NOT ENFORCED"
            rules.append("UNIQUE PRIMARY INDEX -> PRIMARY KEY NONCLUSTERED NOT ENFORCED")
        dist = f"HASH([{t.primary_index[0]}])" if t.primary_index else "ROUND_ROBIN"
        rules.append("PRIMARY INDEX -> DISTRIBUTION = HASH")
        with_opts = [f"DISTRIBUTION = {dist}", "CLUSTERED COLUMNSTORE INDEX"]
        if t.partition_columns:
            warnings.append(f"Partitioning on {t.partition_columns[0]}: add PARTITION ( ... RANGE RIGHT FOR VALUES (...)) boundaries")
        sql = (
            f"IF OBJECT_ID('{schema}.{t.name}') IS NULL\nCREATE TABLE {fqn} (\n    {body}\n)\nWITH (\n    "
            + ",\n    ".join(with_opts)
            + "\n);"
        )
        if t.comment:
            sql += f"\n-- Table comment: {t.comment}\n-- EXEC sp_addextendedproperty is not supported in dedicated SQL pools"
    if t.statistics:
        rules.append(
            "COLLECT STATISTICS -> " + {"bigquery": "dropped (automatic)", "redshift": "ANALYZE", "synapse": "CREATE STATISTICS"}[target]
        )
        if target == "redshift":
            sql += f"\nANALYZE {fqn};"
        elif target == "synapse":
            for i, cols in enumerate(t.statistics, 1):
                sql += f"\nCREATE STATISTICS [st_{t.name}_{i}] ON {fqn} ({', '.join(f'[{c}]' for c in cols)});"
    header = f"-- Source: {t.fqn} ({t.kind} table, {len(t.columns)} columns) from {obj.source_file}\n"
    rules = list(dict.fromkeys(rules))
    warnings = list(dict.fromkeys(warnings))
    return Conversion(
        object_id=obj.id,
        target=target,
        status="converted_with_warnings" if warnings else "converted",
        sql=header + sql + "\n",
        rules=rules,
        warnings=warnings,
    )


def duckdb_ddl(t: TableMeta, schema: str) -> str:
    cols = []
    for c in t.columns:
        s = f'"{c.name}" {duckdb_type(c)}'
        if not c.nullable and not c.identity and c.default is None:
            s += " NOT NULL"
        cols.append(s)
    return f'CREATE OR REPLACE TABLE "{schema}"."{t.name}" (\n    ' + ",\n    ".join(cols) + "\n);"
