/**********************************************************************
 * DIM_ACCOUNT — Account Dimension
 * Teradata MULTISET table with composite primary index
 **********************************************************************/

CREATE MULTISET TABLE BANKING_DW.DIM_ACCOUNT, NO FALLBACK,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
(
    ACCOUNT_KEY         BIGINT           NOT NULL GENERATED ALWAYS AS IDENTITY
                                         (START WITH 1 INCREMENT BY 1),
    ACCOUNT_ID          VARCHAR(20)      NOT NULL,
    CUSTOMER_ID         INTEGER          NOT NULL,
    ACCOUNT_TYPE        VARCHAR(20)      NOT CASESPECIFIC NOT NULL
                                         COMPRESS ('CHECKING', 'SAVINGS', 'LOAN', 'CREDIT_CARD',
                                                   'MORTGAGE', 'DEPOSIT', 'INVESTMENT'),
    ACCOUNT_SUBTYPE     VARCHAR(30)      NOT CASESPECIFIC
                                         COMPRESS ('PERSONAL', 'BUSINESS', 'JOINT', 'TRUST'),
    CURRENCY_CODE       CHAR(3)          NOT CASESPECIFIC DEFAULT 'NOK'
                                         COMPRESS ('NOK', 'EUR', 'USD', 'GBP', 'SEK', 'DKK'),
    OPENING_DATE        DATE FORMAT 'YYYY-MM-DD' NOT NULL,
    CLOSING_DATE        DATE FORMAT 'YYYY-MM-DD',
    ACCOUNT_STATUS      VARCHAR(15)      NOT CASESPECIFIC DEFAULT 'ACTIVE'
                                         COMPRESS ('ACTIVE', 'DORMANT', 'CLOSED', 'FROZEN', 'SUSPENDED'),
    INTEREST_RATE       DECIMAL(7,4),
    CREDIT_LIMIT        DECIMAL(15,2)    COMPRESS 0,
    OVERDRAFT_LIMIT     DECIMAL(15,2)    DEFAULT 0,
    BRANCH_ID           INTEGER,
    RELATIONSHIP_MGR_ID INTEGER          COMPRESS 0,
    PRODUCT_ID          INTEGER          NOT NULL,
    IS_JOINT_ACCOUNT    BYTEINT          DEFAULT 0 COMPRESS (0, 1),
    TAX_REPORTING_FLAG  BYTEINT          DEFAULT 1 COMPRESS (0, 1),
    EFFECTIVE_FROM      TIMESTAMP(0)     DEFAULT CURRENT_TIMESTAMP(0),
    EFFECTIVE_TO        TIMESTAMP(0)     DEFAULT TIMESTAMP '9999-12-31 23:59:59',
    CURRENT_FLAG        CHAR(1)          DEFAULT 'Y' COMPRESS ('Y', 'N'),
    ETL_BATCH_ID        BIGINT,
    ETL_INSERT_TS       TIMESTAMP(0)     DEFAULT CURRENT_TIMESTAMP(0),
    ETL_UPDATE_TS       TIMESTAMP(0)     DEFAULT CURRENT_TIMESTAMP(0)
)
UNIQUE PRIMARY INDEX UPI_ACCOUNT_KEY (ACCOUNT_KEY)
INDEX NUPI_ACCOUNT_ID (ACCOUNT_ID)
INDEX IDX_ACCT_CUSTOMER (CUSTOMER_ID)
INDEX IDX_ACCT_TYPE (ACCOUNT_TYPE)
INDEX IDX_ACCT_BRANCH (BRANCH_ID)
PARTITION BY RANGE_N(OPENING_DATE BETWEEN DATE '2000-01-01'
                                  AND     DATE '2030-12-31'
                                  EACH INTERVAL '1' YEAR);

COLLECT STATISTICS COLUMN (ACCOUNT_ID) ON BANKING_DW.DIM_ACCOUNT;
COLLECT STATISTICS COLUMN (CUSTOMER_ID) ON BANKING_DW.DIM_ACCOUNT;
COLLECT STATISTICS COLUMN (ACCOUNT_TYPE) ON BANKING_DW.DIM_ACCOUNT;
COLLECT STATISTICS COLUMN (ACCOUNT_STATUS) ON BANKING_DW.DIM_ACCOUNT;
COLLECT STATISTICS COLUMN (BRANCH_ID) ON BANKING_DW.DIM_ACCOUNT;

COMMENT ON TABLE BANKING_DW.DIM_ACCOUNT IS 'Account dimension with SCD Type 2 tracking for status and rate changes';
