/**********************************************************************
 * FACT_TRANSACTION — Daily Transaction Fact Table
 * Teradata MULTISET table with Partitioned Primary Index (PPI)
 * This is the largest table in the warehouse — uses PPI on TRANSACTION_DATE
 **********************************************************************/

CREATE MULTISET TABLE BANKING_DW.FACT_TRANSACTION, NO FALLBACK,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
(
    TRANSACTION_ID      BIGINT           NOT NULL,
    TRANSACTION_DATE    DATE FORMAT 'YYYY-MM-DD' NOT NULL,
    TRANSACTION_TIME    TIME(0),
    TRANSACTION_TS      TIMESTAMP(6),
    ACCOUNT_KEY         BIGINT           NOT NULL,
    CUSTOMER_KEY        BIGINT           NOT NULL,
    PRODUCT_ID          INTEGER          NOT NULL,
    BRANCH_ID           INTEGER,
    DATE_KEY            INTEGER          NOT NULL,
    TRANSACTION_TYPE    VARCHAR(20)      NOT CASESPECIFIC NOT NULL
                                         COMPRESS ('DEBIT', 'CREDIT', 'TRANSFER', 'FEE',
                                                   'INTEREST', 'REVERSAL', 'ADJUSTMENT'),
    TRANSACTION_SUBTYPE VARCHAR(30)      NOT CASESPECIFIC
                                         COMPRESS ('ATM_WITHDRAWAL', 'POS_PURCHASE', 'ONLINE_TRANSFER',
                                                   'DIRECT_DEBIT', 'SALARY', 'STANDING_ORDER',
                                                   'CARD_PAYMENT', 'MOBILE_PAYMENT', 'VIPPS'),
    CHANNEL             VARCHAR(20)      NOT CASESPECIFIC
                                         COMPRESS ('BRANCH', 'ATM', 'ONLINE', 'MOBILE', 'POS', 'API'),
    TRANSACTION_AMOUNT  DECIMAL(15,2)    NOT NULL,
    TRANSACTION_CURRENCY CHAR(3)         NOT CASESPECIFIC DEFAULT 'NOK'
                                         COMPRESS ('NOK', 'EUR', 'USD', 'GBP', 'SEK', 'DKK'),
    BASE_CURRENCY_AMOUNT DECIMAL(15,2),
    EXCHANGE_RATE       DECIMAL(12,6)    DEFAULT 1.000000,
    RUNNING_BALANCE     DECIMAL(15,2),
    MERCHANT_ID         VARCHAR(20),
    MERCHANT_NAME       VARCHAR(100)     NOT CASESPECIFIC,
    MERCHANT_CATEGORY   VARCHAR(4),       -- MCC code
    COUNTERPARTY_ACCT   VARCHAR(20),
    REFERENCE_NUMBER    VARCHAR(30),
    DESCRIPTION_TEXT    VARCHAR(200)     NOT CASESPECIFIC,
    IS_INTERNATIONAL    BYTEINT          DEFAULT 0 COMPRESS (0, 1),
    IS_FLAGGED          BYTEINT          DEFAULT 0 COMPRESS (0, 1),
    FLAG_REASON         VARCHAR(50)      COMPRESS '',
    POSTING_DATE        DATE FORMAT 'YYYY-MM-DD',
    VALUE_DATE          DATE FORMAT 'YYYY-MM-DD',
    ETL_BATCH_ID        BIGINT,
    ETL_INSERT_TS       TIMESTAMP(0)     DEFAULT CURRENT_TIMESTAMP(0)
)
PRIMARY INDEX PI_FACT_TXN (ACCOUNT_KEY, TRANSACTION_DATE)
PARTITION BY RANGE_N(TRANSACTION_DATE BETWEEN DATE '2018-01-01'
                                      AND     DATE '2030-12-31'
                                      EACH INTERVAL '1' MONTH,
                     NO RANGE);

COLLECT STATISTICS COLUMN (TRANSACTION_ID) ON BANKING_DW.FACT_TRANSACTION;
COLLECT STATISTICS COLUMN (TRANSACTION_DATE) ON BANKING_DW.FACT_TRANSACTION;
COLLECT STATISTICS COLUMN (ACCOUNT_KEY) ON BANKING_DW.FACT_TRANSACTION;
COLLECT STATISTICS COLUMN (CUSTOMER_KEY) ON BANKING_DW.FACT_TRANSACTION;
COLLECT STATISTICS COLUMN (TRANSACTION_TYPE) ON BANKING_DW.FACT_TRANSACTION;
COLLECT STATISTICS COLUMN (CHANNEL) ON BANKING_DW.FACT_TRANSACTION;
COLLECT STATISTICS COLUMN (PARTITION) ON BANKING_DW.FACT_TRANSACTION;

COMMENT ON TABLE BANKING_DW.FACT_TRANSACTION IS 'Grain: one row per transaction. PPI on TRANSACTION_DATE for partition elimination.';
