CREATE SET TABLE RETAIL_DW.SELLERS, NO FALLBACK, NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
    seller_id               CHAR(32)     CHARACTER SET LATIN   NOT CASESPECIFIC NOT NULL,
    seller_zip_code_prefix  CHAR(5)      CHARACTER SET LATIN   NOT CASESPECIFIC,
    seller_city             VARCHAR(60)  CHARACTER SET UNICODE NOT CASESPECIFIC,
    seller_state            CHAR(2)      CHARACTER SET LATIN   NOT CASESPECIFIC
)
UNIQUE PRIMARY INDEX UPI_SELLERS (seller_id);
