CREATE MULTISET TABLE RETAIL_DW.ORDER_ITEMS, NO FALLBACK, NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
    order_id             CHAR(32)      CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
    order_item_id        SMALLINT      NOT NULL,
    product_id           CHAR(32)      CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
    seller_id            CHAR(32)      CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
    shipping_limit_date  TIMESTAMP(0),
    price                DECIMAL(10,2) NOT NULL,
    freight_value        DECIMAL(10,2),
    FOREIGN KEY (order_id)   REFERENCES WITH NO CHECK OPTION RETAIL_DW.ORDERS (order_id),
    FOREIGN KEY (product_id) REFERENCES WITH NO CHECK OPTION RETAIL_DW.PRODUCTS (product_id),
    FOREIGN KEY (seller_id)  REFERENCES WITH NO CHECK OPTION RETAIL_DW.SELLERS (seller_id)
)
PRIMARY INDEX PI_ORDER_ITEMS (order_id)
UNIQUE INDEX USI_ORDER_ITEMS (order_id, order_item_id);
