-- Business logic validation queries for Snowflake target

-- B-01: CUSTOMER_SEGMENT domain
SELECT DISTINCT CUSTOMER_SEGMENT FROM BANKING_DW.DIM_CUSTOMER ORDER BY 1;

-- B-02: ACCOUNT_TYPE domain
SELECT DISTINCT ACCOUNT_TYPE FROM BANKING_DW.DIM_ACCOUNT ORDER BY 1;

-- B-03: ACCOUNT_STATUS domain
SELECT DISTINCT ACCOUNT_STATUS FROM BANKING_DW.DIM_ACCOUNT ORDER BY 1;

-- B-04: TRANSACTION_TYPE domain
SELECT DISTINCT TRANSACTION_TYPE FROM BANKING_DW.FACT_TRANSACTION ORDER BY 1;

-- B-05: CHANNEL domain
SELECT DISTINCT CHANNEL FROM BANKING_DW.FACT_TRANSACTION ORDER BY 1;

-- B-06: KYC_STATUS domain
SELECT DISTINCT KYC_STATUS FROM BANKING_DW.DIM_CUSTOMER ORDER BY 1;

-- B-07: GENDER domain
SELECT DISTINCT GENDER FROM BANKING_DW.DIM_CUSTOMER ORDER BY 1;

-- B-08: DIM_DATE range
SELECT MIN(CALENDAR_DATE) AS MIN_DATE, MAX(CALENDAR_DATE) AS MAX_DATE
FROM BANKING_DW.DIM_DATE;

-- B-09: DATE_KEY format check
SELECT COUNT(*) AS MISMATCHES
FROM BANKING_DW.DIM_DATE
WHERE DATE_KEY != CAST(TO_CHAR(CALENDAR_DATE, 'YYYYMMDD') AS INTEGER);

-- B-10: Snapshot OPENING_BALANCE = prior CLOSING_BALANCE
SELECT COUNT(*) AS MISMATCHES
FROM BANKING_DW.FACT_MONTHLY_ACCOUNT_SNAPSHOT curr
INNER JOIN BANKING_DW.FACT_MONTHLY_ACCOUNT_SNAPSHOT prev
    ON curr.ACCOUNT_KEY = prev.ACCOUNT_KEY
   AND prev.SNAPSHOT_MONTH_KEY = (
       CASE
           WHEN curr.SNAPSHOT_MONTH_KEY % 100 = 1
           THEN (FLOOR(curr.SNAPSHOT_MONTH_KEY / 100) - 1) * 100 + 12
           ELSE curr.SNAPSHOT_MONTH_KEY - 1
       END
   )
WHERE ABS(curr.OPENING_BALANCE - prev.CLOSING_BALANCE) > 0.01;

-- B-11: CLOSING_BALANCE = OPENING + CREDITS - DEBITS
SELECT COUNT(*) AS MISMATCHES
FROM BANKING_DW.FACT_MONTHLY_ACCOUNT_SNAPSHOT
WHERE ABS(CLOSING_BALANCE - (OPENING_BALANCE + TOTAL_CREDITS - TOTAL_DEBITS)) > 0.01;

-- B-12: Regulatory view threshold logic
SELECT COUNT(*) AS VIOLATIONS
FROM BANKING_DW.VW_REGULATORY_LARGE_TRANSACTIONS
WHERE BASE_CURRENCY_AMOUNT < 100000
  AND NOT (IS_INTERNATIONAL = 1 AND BASE_CURRENCY_AMOUNT >= 25000)
  AND IS_FLAGGED != 1;

-- B-13: IS_INTERNATIONAL flag logic
SELECT COUNT(*) AS MISMATCHES
FROM BANKING_DW.FACT_TRANSACTION
WHERE TRANSACTION_CURRENCY != 'NOK' AND IS_INTERNATIONAL != 1;

-- B-14: CURRENT_FLAG SCD2 — one Y per natural key in DIM_CUSTOMER
SELECT CUSTOMER_ID, COUNT(*) AS CNT
FROM BANKING_DW.DIM_CUSTOMER
WHERE CURRENT_FLAG = 'Y'
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

-- B-15: EFFECTIVE_FROM < EFFECTIVE_TO
SELECT COUNT(*) AS VIOLATIONS
FROM BANKING_DW.DIM_CUSTOMER
WHERE EFFECTIVE_FROM >= EFFECTIVE_TO;

-- B-16: CURRENCY_CODE domain (DIM_ACCOUNT)
SELECT DISTINCT CURRENCY_CODE FROM BANKING_DW.DIM_ACCOUNT ORDER BY 1;

-- B-17: BRANCH_TYPE domain
SELECT DISTINCT BRANCH_TYPE FROM BANKING_DW.DIM_BRANCH ORDER BY 1;

-- B-18: REGION domain
SELECT DISTINCT REGION FROM BANKING_DW.DIM_BRANCH ORDER BY 1;
