-- Data integrity & checksum queries for Snowflake target

-- D-01: DIM_CUSTOMER aggregate checksum
SELECT
    COUNT(*)                              AS ROW_COUNT,
    COUNT(DISTINCT CUSTOMER_ID)           AS DISTINCT_CUSTOMERS,
    MIN(ONBOARDING_DATE)                  AS MIN_ONBOARD_DATE,
    MAX(ONBOARDING_DATE)                  AS MAX_ONBOARD_DATE,
    SUM(CASE WHEN IS_ACTIVE = 1 THEN 1 ELSE 0 END) AS ACTIVE_COUNT
FROM BANKING_DW.DIM_CUSTOMER
WHERE CURRENT_FLAG = 'Y';

-- D-02: FACT_TRANSACTION aggregate checksum per month
SELECT
    EXTRACT(YEAR FROM TRANSACTION_DATE)  AS TXN_YEAR,
    EXTRACT(MONTH FROM TRANSACTION_DATE) AS TXN_MONTH,
    COUNT(*)                             AS TXN_COUNT,
    SUM(TRANSACTION_AMOUNT)              AS TOTAL_AMOUNT,
    SUM(BASE_CURRENCY_AMOUNT)            AS TOTAL_BASE_AMOUNT
FROM BANKING_DW.FACT_TRANSACTION
GROUP BY 1, 2
ORDER BY 1, 2;

-- D-03: Monthly snapshot balance totals
SELECT
    SNAPSHOT_MONTH_KEY,
    SUM(CLOSING_BALANCE) AS TOTAL_CLOSING,
    SUM(TOTAL_DEBITS)    AS TOTAL_DEBITS,
    SUM(TOTAL_CREDITS)   AS TOTAL_CREDITS
FROM BANKING_DW.FACT_MONTHLY_ACCOUNT_SNAPSHOT
GROUP BY 1
ORDER BY 1;

-- D-04: Duplicate primary keys — DIM_CUSTOMER
SELECT CUSTOMER_KEY, COUNT(*) AS CNT
FROM BANKING_DW.DIM_CUSTOMER
GROUP BY CUSTOMER_KEY
HAVING COUNT(*) > 1;

-- D-05: Duplicate primary keys — DIM_ACCOUNT
SELECT ACCOUNT_KEY, COUNT(*) AS CNT
FROM BANKING_DW.DIM_ACCOUNT
GROUP BY ACCOUNT_KEY
HAVING COUNT(*) > 1;

-- D-06: Duplicate TRANSACTION_IDs
SELECT TRANSACTION_ID, COUNT(*) AS CNT
FROM BANKING_DW.FACT_TRANSACTION
GROUP BY TRANSACTION_ID
HAVING COUNT(*) > 1;

-- D-09: SCD2 current flag consistency (one Y per natural key)
SELECT CUSTOMER_ID, COUNT(*) AS CNT
FROM BANKING_DW.DIM_CUSTOMER
WHERE CURRENT_FLAG = 'Y'
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

-- D-11: Full-row duplicate check (SET table equivalents)
-- DIM_PRODUCT as representative SET table
SELECT COUNT(*) AS DUPLICATE_GROUPS
FROM (
    SELECT PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_CATEGORY,
           PRODUCT_SUBCATEGORY, BASE_INTEREST_RATE, MIN_BALANCE, MAX_BALANCE,
           FEE_STRUCTURE, MONTHLY_FEE, IS_REGULATED, REGULATORY_CODE,
           LAUNCH_DATE, DISCONTINUE_DATE, IS_ACTIVE, ETL_BATCH_ID, ETL_INSERT_TS
    FROM BANKING_DW.DIM_PRODUCT
    GROUP BY ALL
    HAVING COUNT(*) > 1
);

-- D-12: DIM_PRODUCT aggregate checksum
SELECT
    COUNT(*)                           AS ROW_COUNT,
    COUNT(DISTINCT PRODUCT_CODE)       AS DISTINCT_PRODUCTS,
    SUM(CASE WHEN IS_ACTIVE = 1 THEN 1 ELSE 0 END) AS ACTIVE_COUNT
FROM BANKING_DW.DIM_PRODUCT;

-- D-13: DIM_BRANCH aggregate checksum
SELECT
    COUNT(*)                           AS ROW_COUNT,
    COUNT(DISTINCT BRANCH_CODE)        AS DISTINCT_BRANCHES,
    COUNT(DISTINCT REGION)             AS DISTINCT_REGIONS
FROM BANKING_DW.DIM_BRANCH;
