-- ================================================================
-- Data Integrity & Checksum Queries (Category 3: D-01 to D-13)
-- ================================================================

-- D-01: DIM_CUSTOMER aggregate checksum
SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT CUSTOMER_ID) AS DISTINCT_CUSTOMERS,
    MIN(ONBOARDING_DATE) AS MIN_ONBOARD_DATE,
    MAX(ONBOARDING_DATE) AS MAX_ONBOARD_DATE,
    SUM(CASE WHEN IS_ACTIVE = 1 THEN 1 ELSE 0 END) AS ACTIVE_COUNT
FROM {schema}.DIM_CUSTOMER
WHERE CURRENT_FLAG = 'Y';

-- D-02: FACT_TRANSACTION aggregate checksum per month
SELECT
    EXTRACT(YEAR FROM TRANSACTION_DATE) AS TXN_YEAR,
    EXTRACT(MONTH FROM TRANSACTION_DATE) AS TXN_MONTH,
    COUNT(*) AS TXN_COUNT,
    SUM(TRANSACTION_AMOUNT) AS TOTAL_AMOUNT,
    SUM(BASE_CURRENCY_AMOUNT) AS TOTAL_BASE_AMOUNT,
    COUNT(DISTINCT ACCOUNT_KEY) AS DISTINCT_ACCOUNTS,
    COUNT(DISTINCT CUSTOMER_KEY) AS DISTINCT_CUSTOMERS
FROM {schema}.FACT_TRANSACTION
GROUP BY TXN_YEAR, TXN_MONTH
ORDER BY TXN_YEAR, TXN_MONTH;

-- D-03: Monthly snapshot balance totals
SELECT
    SNAPSHOT_MONTH_KEY,
    SUM(CLOSING_BALANCE) AS TOTAL_CLOSING,
    SUM(TOTAL_DEBITS) AS TOTAL_DEBITS,
    SUM(TOTAL_CREDITS) AS TOTAL_CREDITS
FROM {schema}.FACT_MONTHLY_ACCOUNT_SNAPSHOT
GROUP BY SNAPSHOT_MONTH_KEY
ORDER BY SNAPSHOT_MONTH_KEY;

-- D-04: Duplicate primary keys in DIM_CUSTOMER
SELECT CUSTOMER_KEY, COUNT(*) AS CNT
FROM {schema}.DIM_CUSTOMER
GROUP BY CUSTOMER_KEY
HAVING COUNT(*) > 1;

-- D-05: Duplicate primary keys in DIM_ACCOUNT
SELECT ACCOUNT_KEY, COUNT(*) AS CNT
FROM {schema}.DIM_ACCOUNT
GROUP BY ACCOUNT_KEY
HAVING COUNT(*) > 1;

-- D-06: Duplicate TRANSACTION_IDs
SELECT TRANSACTION_ID, COUNT(*) AS CNT
FROM {schema}.FACT_TRANSACTION
GROUP BY TRANSACTION_ID
HAVING COUNT(*) > 1;

-- D-07: MIN/MAX ONBOARDING_DATE ranges
SELECT
    MIN(ONBOARDING_DATE) AS MIN_DATE,
    MAX(ONBOARDING_DATE) AS MAX_DATE
FROM {schema}.DIM_CUSTOMER;

-- D-08: MIN/MAX TRANSACTION_DATE ranges
SELECT
    MIN(TRANSACTION_DATE) AS MIN_DATE,
    MAX(TRANSACTION_DATE) AS MAX_DATE
FROM {schema}.FACT_TRANSACTION;

-- D-09: SCD2 current flag consistency
-- Each CUSTOMER_ID should have exactly one row with CURRENT_FLAG = 'Y'
SELECT CUSTOMER_ID, COUNT(*) AS CURRENT_COUNT
FROM {schema}.DIM_CUSTOMER
WHERE CURRENT_FLAG = 'Y'
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

-- D-10: DECIMAL precision preserved
SELECT
    SUM(TRANSACTION_AMOUNT) AS SUM_AMT,
    AVG(TRANSACTION_AMOUNT) AS AVG_AMT,
    MIN(TRANSACTION_AMOUNT) AS MIN_AMT,
    MAX(TRANSACTION_AMOUNT) AS MAX_AMT
FROM {schema}.FACT_TRANSACTION;

-- D-11: Full-row duplicate check (SET table equivalents)
-- DIM_CUSTOMER
SELECT COUNT(*) AS DUPE_GROUPS
FROM (
    SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, GENDER,
           MARITAL_STATUS, EMAIL_ADDRESS, CUSTOMER_SEGMENT, IS_ACTIVE,
           EFFECTIVE_FROM, EFFECTIVE_TO, CURRENT_FLAG
    FROM {schema}.DIM_CUSTOMER
    GROUP BY CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, GENDER,
             MARITAL_STATUS, EMAIL_ADDRESS, CUSTOMER_SEGMENT, IS_ACTIVE,
             EFFECTIVE_FROM, EFFECTIVE_TO, CURRENT_FLAG
    HAVING COUNT(*) > 1
);

-- D-12: DIM_PRODUCT aggregate checksum
SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT PRODUCT_CODE) AS DISTINCT_PRODUCTS,
    SUM(CASE WHEN IS_ACTIVE = 1 THEN 1 ELSE 0 END) AS ACTIVE_COUNT
FROM {schema}.DIM_PRODUCT;

-- D-13: DIM_BRANCH aggregate checksum
SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT BRANCH_CODE) AS DISTINCT_BRANCHES,
    COUNT(DISTINCT REGION) AS DISTINCT_REGIONS
FROM {schema}.DIM_BRANCH;
