-- Edge case & boundary queries for Snowflake target

-- E-01: Boundary — DIM_DATE has 2000-01-01
SELECT COUNT(*) AS CNT FROM BANKING_DW.DIM_DATE WHERE CALENDAR_DATE = '2000-01-01';

-- E-02: Boundary — DIM_DATE has 2029-12-31
SELECT COUNT(*) AS CNT FROM BANKING_DW.DIM_DATE WHERE CALENDAR_DATE = '2029-12-31';

-- E-03: SCD2 sentinel — EFFECTIVE_TO = '9999-12-31 23:59:59' for current records (DIM_CUSTOMER)
SELECT COUNT(*) AS VIOLATIONS
FROM BANKING_DW.DIM_CUSTOMER
WHERE CURRENT_FLAG = 'Y'
  AND EFFECTIVE_TO != '9999-12-31 23:59:59';

-- E-04: Max TRANSACTION_AMOUNT
SELECT MAX(TRANSACTION_AMOUNT) AS MAX_AMT FROM BANKING_DW.FACT_TRANSACTION;

-- E-05: Min (negative) TRANSACTION_AMOUNT
SELECT MIN(TRANSACTION_AMOUNT) AS MIN_AMT FROM BANKING_DW.FACT_TRANSACTION;

-- E-06: Zero-amount transactions
SELECT COUNT(*) AS ZERO_AMT_COUNT FROM BANKING_DW.FACT_TRANSACTION WHERE TRANSACTION_AMOUNT = 0;

-- E-07: Norwegian special characters (ae/oe/aa) in DIM_BRANCH
SELECT COUNT(*) AS SPECIAL_CHAR_COUNT
FROM BANKING_DW.DIM_BRANCH
WHERE BRANCH_NAME LIKE '%ø%'
   OR BRANCH_NAME LIKE '%æ%'
   OR BRANCH_NAME LIKE '%å%'
   OR CITY LIKE '%ø%'
   OR CITY LIKE '%æ%'
   OR CITY LIKE '%å%';

-- E-08: EXCHANGE_RATE 6 decimal places
SELECT COUNT(*) AS NON_DEFAULT_RATES
FROM BANKING_DW.FACT_TRANSACTION
WHERE EXCHANGE_RATE != 1.000000
  AND EXCHANGE_RATE IS NOT NULL;

-- E-09: Partition boundary dates (1st/last day of month)
SELECT
    EXTRACT(YEAR FROM TRANSACTION_DATE)  AS Y,
    EXTRACT(MONTH FROM TRANSACTION_DATE) AS M,
    MIN(TRANSACTION_DATE) AS FIRST_TXN,
    MAX(TRANSACTION_DATE) AS LAST_TXN
FROM BANKING_DW.FACT_TRANSACTION
GROUP BY 1, 2
ORDER BY 1, 2;

-- E-10: Leap year Feb 29
SELECT COUNT(*) AS LEAP_DAYS
FROM BANKING_DW.DIM_DATE
WHERE MONTH_NUM = 2 AND DAY_OF_MONTH = 29;

-- E-11: NULL BRANCH_ID (online/mobile transactions)
SELECT COUNT(*) AS NULL_BRANCH_COUNT
FROM BANKING_DW.FACT_TRANSACTION
WHERE BRANCH_ID IS NULL;

-- E-12: Multi-currency EUR accounts
SELECT COUNT(*) AS EUR_ACCOUNTS
FROM BANKING_DW.DIM_ACCOUNT
WHERE CURRENCY_CODE = 'EUR';

-- E-13: TIMESTAMP(6) microsecond precision
SELECT COUNT(*) AS HAS_MICROSECONDS
FROM BANKING_DW.FACT_TRANSACTION
WHERE TRANSACTION_TS IS NOT NULL
  AND EXTRACT(MICROSECOND FROM TRANSACTION_TS) != 0;

-- E-14: IS_WEEKEND vs IS_BUSINESS_DAY consistency
SELECT COUNT(*) AS INCONSISTENT
FROM BANKING_DW.DIM_DATE
WHERE IS_WEEKEND = 1 AND IS_BUSINESS_DAY = 1 AND IS_NORWEGIAN_HOLIDAY = 0;

-- E-15: SNAPSHOT_MONTH_KEY format
SELECT COUNT(*) AS MISMATCHES
FROM BANKING_DW.FACT_MONTHLY_ACCOUNT_SNAPSHOT
WHERE SNAPSHOT_MONTH_KEY !=
      EXTRACT(YEAR FROM SNAPSHOT_DATE) * 100 + EXTRACT(MONTH FROM SNAPSHOT_DATE);

-- E-16: SCD2 sentinel in DIM_ACCOUNT
SELECT COUNT(*) AS VIOLATIONS
FROM BANKING_DW.DIM_ACCOUNT
WHERE CURRENT_FLAG = 'Y'
  AND EFFECTIVE_TO != '9999-12-31 23:59:59';

-- E-17: Fiscal year alignment
SELECT COUNT(*) AS VIOLATIONS
FROM BANKING_DW.DIM_DATE
WHERE ABS(FISCAL_YEAR - CALENDAR_YEAR) > 1;
