-- Row count validation queries for Snowflake target
-- Reference: data/validation/expected_row_counts.csv

-- R-01 to R-07: Per-table row counts
SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM BANKING_DW.DIM_CUSTOMER
UNION ALL
SELECT 'DIM_ACCOUNT', COUNT(*) FROM BANKING_DW.DIM_ACCOUNT
UNION ALL
SELECT 'DIM_PRODUCT', COUNT(*) FROM BANKING_DW.DIM_PRODUCT
UNION ALL
SELECT 'DIM_BRANCH', COUNT(*) FROM BANKING_DW.DIM_BRANCH
UNION ALL
SELECT 'DIM_DATE', COUNT(*) FROM BANKING_DW.DIM_DATE
UNION ALL
SELECT 'FACT_TRANSACTION', COUNT(*) FROM BANKING_DW.FACT_TRANSACTION
UNION ALL
SELECT 'FACT_MONTHLY_ACCOUNT_SNAPSHOT', COUNT(*) FROM BANKING_DW.FACT_MONTHLY_ACCOUNT_SNAPSHOT
ORDER BY 1;

-- R-08: Row counts per partition (FACT_TRANSACTION by year-month)
SELECT
    EXTRACT(YEAR FROM TRANSACTION_DATE)  AS TXN_YEAR,
    EXTRACT(MONTH FROM TRANSACTION_DATE) AS TXN_MONTH,
    COUNT(*)                             AS ROW_COUNT
FROM BANKING_DW.FACT_TRANSACTION
GROUP BY 1, 2
ORDER BY 1, 2;

-- R-09: Distinct key counts per table
SELECT 'DIM_CUSTOMER'  AS TABLE_NAME, COUNT(DISTINCT CUSTOMER_KEY) AS DISTINCT_KEYS FROM BANKING_DW.DIM_CUSTOMER
UNION ALL
SELECT 'DIM_ACCOUNT',  COUNT(DISTINCT ACCOUNT_KEY) FROM BANKING_DW.DIM_ACCOUNT
UNION ALL
SELECT 'DIM_PRODUCT',  COUNT(DISTINCT PRODUCT_ID)  FROM BANKING_DW.DIM_PRODUCT
UNION ALL
SELECT 'DIM_BRANCH',   COUNT(DISTINCT BRANCH_ID)   FROM BANKING_DW.DIM_BRANCH
UNION ALL
SELECT 'DIM_DATE',     COUNT(DISTINCT DATE_KEY)     FROM BANKING_DW.DIM_DATE
UNION ALL
SELECT 'FACT_TRANSACTION', COUNT(DISTINCT TRANSACTION_ID) FROM BANKING_DW.FACT_TRANSACTION
UNION ALL
SELECT 'FACT_MONTHLY_ACCOUNT_SNAPSHOT', COUNT(DISTINCT ACCOUNT_KEY) FROM BANKING_DW.FACT_MONTHLY_ACCOUNT_SNAPSHOT
ORDER BY 1;
