-- Schema validation queries for Snowflake target

-- S-01: Verify all tables exist
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'BANKING_DW'
  AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

-- S-02: Verify all views exist
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'BANKING_DW'
ORDER BY TABLE_NAME;

-- S-03: Column count per table
SELECT TABLE_NAME, COUNT(*) AS COLUMN_COUNT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'BANKING_DW'
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;

-- S-04: Column names for a specific table (parameterised)
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'BANKING_DW'
  AND TABLE_NAME = %s
ORDER BY ORDINAL_POSITION;

-- S-05: Column data types
SELECT COLUMN_NAME, DATA_TYPE, NUMERIC_PRECISION, NUMERIC_SCALE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'BANKING_DW'
  AND TABLE_NAME = %s
ORDER BY ORDINAL_POSITION;

-- S-06: NOT NULL constraints
SELECT COLUMN_NAME, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'BANKING_DW'
  AND TABLE_NAME = %s
ORDER BY ORDINAL_POSITION;

-- S-07: DEFAULT values
SELECT COLUMN_NAME, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'BANKING_DW'
  AND TABLE_NAME = %s
  AND COLUMN_DEFAULT IS NOT NULL
ORDER BY ORDINAL_POSITION;

-- S-08: IDENTITY / AUTOINCREMENT columns
SELECT COLUMN_NAME, IS_IDENTITY
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'BANKING_DW'
  AND TABLE_NAME = %s
  AND IS_IDENTITY = 'YES'
ORDER BY ORDINAL_POSITION;

-- S-09: TIMESTAMP column types
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'BANKING_DW'
  AND TABLE_NAME = %s
  AND DATA_TYPE LIKE 'TIMESTAMP%%'
ORDER BY ORDINAL_POSITION;
